### ISSUE TITLE
Dashboard Wont Load on select campaigns

### ISSUE THREAD

**Issue by Adusei** [unicef/rhizome#6]
for instance: 
http://rhizome.work/datapoints/management-dashboard/Nigeria/2015/04

The page wont load and when i look at the console i see:

-  Unhandled promise rejection TypeError: Cannot read property '1' of undefined(…)

**Comment by zhangsichu** [comment]
fixed at the commit 6d943657c48692dcacce242d5f8230ef96bb06a7

**Comment by Adusei** [comment]
@lrrfantasy / @zhangsichu  this is still broken.  Here is the way i got this error:

1.  go to http://rhizome.work/datapoints/management-dashboard/Nigeria/2014/11
2.  switch drop down to Nigeria November 2014.
3.  Open Console: see this error:

Unhandled promise rejection TypeError: Cannot read property '1' of undefined

**Comment by Adusei** [comment]
fixed on production.

**Comment by Adusei** [comment]
http://rhizome.work/datapoints/management-dashboard/Nigeria/2015/06/

BREAKS.
